//@ sourceMappingURL=01_coloredCanvas.map
// Generated by CoffeeScript 1.6.1
(function() {

  require(['cv/Component', 'cv/bindToCanvas'], function(Component, bindToCanvas) {
    var ColoredCanvas, cc, r, randomColor;
    window.C = Component;
    ColoredCanvas = Component.extend({
      paint: function(ctx, bounds) {
        ctx.fillStyle = randomColor();
        return ctx.fillRect(bounds.x, bounds.y, bounds.w, bounds.h);
      }
    });
    randomColor = function() {
      return "rgb(" + (r()) + "," + (r()) + "," + (r()) + ")";
    };
    r = function() {
      return Math.floor(Math.random() * 255);
    };
    cc = new ColoredCanvas;
    setInterval((function() {
      return cc.trigger('graphicsDirty');
    }), 1000);
    return bindToCanvas('coloredCanvas', cc);
  });

}).call(this);
