//@ sourceMappingURL=01_coloredCanvas.map
// Generated by CoffeeScript 1.6.1
(function() {

  require(['cv/Component', 'cv/bindToCanvas'], function(Component, bindToCanvas) {
    var component, r, randomColor;
    component = new Component({
      paint: function(ctx, bounds) {
        ctx.fillStyle = randomColor();
        return ctx.fillRect(bounds.x, bounds.y, bounds.w, bounds.h);
      }
    });
    randomColor = function() {
      return "rgb(" + (r()) + "," + (r()) + "," + (r()) + ")";
    };
    r = function() {
      return Math.floor(Math.random() * 255);
    };
    setInterval((function() {
      return component.trigger('graphicsDirty');
    }), 1000);
    return bindToCanvas('coloredCanvas', component);
  });

}).call(this);
