//@ sourceMappingURL=01_coloredCanvas.map
// Generated by CoffeeScript 1.6.1
(function() {

  require(['cv/Component', 'cv/bindToCanvas'], function(Component, bindToCanvas) {
    var ColoredCanvas, r, randomColor;
    ColoredCanvas = Component.extend({
      initialize: function() {
        var _this = this;
        return setInterval((function() {
          return _this.trigger('graphicsDirty');
        }), 1000);
      },
      paint: function(ctx, bounds) {
        ctx.fillStyle = randomColor();
        return ctx.fillRect(bounds.x, bounds.y, bounds.w, bounds.h);
      }
    });
    randomColor = function() {
      return "rgb(" + (r()) + "," + (r()) + "," + (r()) + ")";
    };
    r = function() {
      return Math.floor(Math.random() * 255);
    };
    return bindToCanvas('coloredCanvas', new ColoredCanvas);
  });

}).call(this);
