//@ sourceMappingURL=02_ScatterPlot.map
// Generated by CoffeeScript 1.6.1
(function() {

  require(['cv/Component', 'cv/bindToCanvas', 'cv/readCSV', 'cv/Viewport', 'cv/Rectangle', 'cv/Point', 'cv/mark'], function(Component, bindToCanvas, readCSV, Viewport, Rectangle, Point, mark) {
    return readCSV('../data/iris.csv', function(err, relation) {
      var ScatterPlot, destPt, srcPt, viewport, xAttr, yAttr;
      xAttr = relation.attributes.at(0);
      yAttr = relation.attributes.at(1);
      srcPt = new Point;
      destPt = new Point;
      viewport = new Viewport({
        src: new Rectangle({
          x: xAttr.min,
          y: yAttr.min,
          w: xAttr.max - xAttr.min,
          h: yAttr.max - yAttr.min
        }),
        dest: new Rectangle
      });
      ScatterPlot = Component.extend({
        paint: function(ctx, bounds) {
          viewport.dest.copy(bounds);
          return relation.tuples.each(function(tuple) {
            return mark().x(tuple.value(xAttr)).y(tuple.value(yAttr)).size(0.1).render(ctx, viewport);
          });
        }
      });
      return bindToCanvas('scatterPlot', new ScatterPlot);
    });
  });

}).call(this);
