//@ sourceMappingURL=02_ScatterPlot.map
// Generated by CoffeeScript 1.6.1
(function() {

  require(['cv/Component', 'cv/bindToCanvas', 'cv/readCSV', 'cv/Viewport', 'cv/Rectangle', 'cv/Point'], function(Component, bindToCanvas, readCSV, Viewport, Rectangle, Point) {
    return readCSV('../data/iris.csv', function(err, relation) {
      var component, destPt, srcPt, viewport, xAttr, yAttr;
      xAttr = relation.attributes.at(0);
      yAttr = relation.attributes.at(1);
      srcPt = new Point;
      destPt = new Point;
      viewport = new Viewport({
        src: new Rectangle({
          x: xAttr.min,
          y: yAttr.min,
          w: xAttr.max - xAttr.min,
          h: yAttr.max - yAttr.min
        }),
        dest: new Rectangle
      });
      component = new Component({
        paint: function(ctx, bounds) {
          viewport.dest.copy(bounds);
          return relation.tuples.each(function(tuple) {
            srcPt.x = tuple.value(xAttr);
            srcPt.y = tuple.value(yAttr);
            viewport.srcToDest(srcPt, destPt);
            return ctx.fillRect(destPt.x, destPt.y, 5, 5);
          });
        }
      });
      return bindToCanvas('scatterPlot', component);
    });
  });

}).call(this);
