//@ sourceMappingURL=circles.map
// Generated by CoffeeScript 1.6.1
(function() {

  require(['cv/Component', 'cv/ViewportContainer', 'cv/Circle'], function(Component, ViewportContainer, Circle) {
    var container;
    container = ViewportContainer.create();
    container.add(new Circle({
      x: 0.5,
      y: 0.5,
      radius: 0.5
    }));
    return Component.bindToCanvas('circles', container);
  });

}).call(this);
