//@ sourceMappingURL=draggableCircle.map
// Generated by CoffeeScript 1.6.1
(function() {

  require(['cv/Component', 'cv/ViewportContainer', 'cv/Circle'], function(Component, ViewportContainer, Circle) {
    var circle, container;
    container = ViewportContainer.create();
    circle = Circle.create(0.5, 0.5, 0.2);
    circle.on('drag', function(x, y) {
      return circle.setXY(x, y);
    });
    window.c = container;
    container.add(circle);
    return Component.bindToCanvas('draggableCircle', container);
  });

}).call(this);
