//@ sourceMappingURL=redCanvas.map
// Generated by CoffeeScript 1.6.1
(function() {

  require(['cv/Component', 'cv/bindToCanvas'], function(Component, bindToCanvas) {
    var component;
    component = new Component({
      paint: function(ctx, bounds) {
        ctx.fillStyle = 'red';
        return ctx.fillRect(bounds.x, bounds.y, bounds.w, bounds.h);
      }
    });
    return bindToCanvas('redCanvas', component);
  });

}).call(this);
