// Generated by CoffeeScript 1.6.1
(function() {

  require(['cv/Component'], function(Component) {
    var component;
    component = Component.create({
      paint: function(ctx, bounds) {
        ctx.fillStyle = 'red';
        return ctx.fillRect(bounds.x, bounds.y, bounds.w, bounds.h);
      }
    });
    return Component.bindToCanvas('redCanvas', component);
  });

}).call(this);
