//@ sourceMappingURL=bindToCanvas.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['requestAnimFrame', 'cv/Rectangle'], function(requestAnimFrame, Rectangle) {
    return function(canvasId, component) {
      var bounds, canvas, ctx, executeFrame, graphicsDirty;
      canvas = document.getElementById(canvasId);
      if (!canvas) {
        throw Error("Invalid Canvas ID: '" + canvasId + "'");
      }
      ctx = canvas.getContext('2d');
      bounds = new Rectangle({
        x: 0,
        y: 0,
        w: canvas.width,
        h: canvas.height
      });
      graphicsDirty = true;
      component.on('graphicsDirty', function() {
        return graphicsDirty = true;
      });
      executeFrame = function() {
        if (graphicsDirty) {
          bounds.w = canvas.width;
          bounds.h = canvas.height;
          component.paint(ctx, bounds);
          graphicsDirty = false;
        }
        return requestAnimFrame(executeFrame);
      };
      return executeFrame();
    };
  });

}).call(this);
