// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/Component'], function(Component) {
    return {
      create: function(x, y, radius) {
        return Component.create({
          paint: function(ctx, bounds) {
            ctx.fillStyle = 'black';
            ctx.beginPath();
            ctx.arc(bounds.centerX, bounds.centerY, (bounds.w + bounds.h) / 4, 0, 2 * Math.PI, false);
            return ctx.fill();
          }
        });
      }
    };
  });

}).call(this);
