// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/Component', 'backbone'], function(Component, Backbone) {
    return Backbone.Model.extend({
      paint: function(ctx, bounds) {
        ctx.fillStyle = 'black';
        ctx.beginPath();
        ctx.arc(bounds.centerX, bounds.centerY, (bounds.w + bounds.h) / 4, 0, 2 * Math.PI, false);
        return ctx.fill();
      },
      getBoundingBox: function(boundingBox) {
        var r2, radius, x, y;
        x = this.get('x');
        y = this.get('y');
        radius = this.get('radius');
        r2 = radius * 2;
        return boundingBox.set(x - radius, y - radius, r2, r2);
      }
    });
  });

}).call(this);
