// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/Component'], function(Component) {
    return {
      create: function(x, y, radius) {
        var circle;
        circle = Component.create({
          paint: function(ctx, bounds) {
            ctx.fillStyle = 'black';
            ctx.beginPath();
            ctx.arc(bounds.centerX, bounds.centerY, (bounds.w + bounds.h) / 4, 0, 2 * Math.PI, false);
            return ctx.fill();
          }
        });
        circle.getBoundingBox = function(boundingBox) {
          var r2;
          r2 = radius * 2;
          return boundingBox.set(x - radius, y - radius, r2, r2);
        };
        return circle;
      }
    };
  });

}).call(this);
