//@ sourceMappingURL=Component.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/expose'], function(expose) {
    return Backbone.Model.extend({
      initialize: function() {
        return expose(this, 'paint');
      }
    });
  });

}).call(this);
