// Generated by CoffeeScript 1.6.1
(function() {

  define(['underscore', 'backbone', 'requestAnimFrame', 'cv/Rectangle'], function(_, Backbone, requestAnimFrame, Rectangle) {
    return {
      create: function(options) {
        return _.extend(new Backbone.Model, options);
      },
      bindToCanvas: function(canvasId, component) {
        var bounds, canvas, ctx, executeFrame, graphicsDirty;
        canvas = document.getElementById(canvasId);
        if (!canvas) {
          throw Error("Invalid Canvas ID: '" + canvasId + "'");
        }
        ctx = canvas.getContext('2d');
        bounds = Rectangle.create(0, 0, canvas.width, canvas.height);
        graphicsDirty = true;
        component.on('graphicsDirty', function() {
          return graphicsDirty = true;
        });
        executeFrame = function() {
          if (graphicsDirty) {
            component.paint(ctx, bounds);
            graphicsDirty = false;
          }
          return requestAnimFrame(executeFrame);
        };
        return executeFrame();
      }
    };
  });

}).call(this);
