//@ sourceMappingURL=Container.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/Component'], function(Component) {
    return {
      create: function(options) {
        var container;
        container = new Component(options);
        _.extend(container, new Backbone.Collection);
        container.on('add', function() {
          return container.trigger('graphicsDirty');
        });
        return container;
      }
    };
  });

}).call(this);
