//@ sourceMappingURL=Container.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/Component'], function(Component) {
    return Component.extend({
      initialize: function() {
        var _this = this;
        this.children = new Backbone.Collection;
        return this.children.on('add remove graphicsDirty', function() {
          return _this.trigger('graphicsDirty');
        });
      }
    });
  });

}).call(this);
