// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/Component', 'underscore', 'backbone'], function(Component, _, Backbone) {
    return {
      create: function(options) {
        var container;
        container = Component.create(options);
        _.extend(container, new Backbone.Collection);
        container.on('add', function() {
          return container.trigger('graphicsDirty');
        });
        return container;
      }
    };
  });

}).call(this);
