//@ sourceMappingURL=expose.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __slice = [].slice;

  define([], function() {
    return function() {
      var model, properties;
      model = arguments[0], properties = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if (!model) {
        throw Error("'model' argument to `expose` is null!'");
      }
      return _.each(properties, function(p) {
        model.__defineGetter__(p, function() {
          return model.get(p);
        });
        return model.__defineSetter__(p, function(val) {
          return model.set(p, val);
        });
      });
    };
  });

}).call(this);
