//@ sourceMappingURL=grammarOfGraphics.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/grammarOfGraphics/parser', 'cv/match', 'cv/Varset'], function(parser, match, Varset) {
    var algebra, execute, show, step3, variables;
    execute = function(columns, expression) {
      var scales, tree, vars;
      tree = parser.parse(expression);
      vars = variables(tree, columns);
      tree = algebra(tree, vars);
      scales = step3(tree);
      console.log(scales);
      return tree;
    };
    variables = function(tree, columns) {
      var stmt, vars, _i, _len, _ref;
      vars = _.extend({}, columns);
      _ref = tree.statements;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        stmt = _ref[_i];
        if (stmt.type === 'data') {
          vars[stmt.newName] = columns[stmt.oldName];
        }
      }
      return vars;
    };
    algebra = match('type', 'algebra', {
      'statements': function(stmts, vars) {
        var stmt;
        return {
          type: 'statements',
          statements: (function() {
            var _i, _len, _ref, _results;
            _ref = stmts.statements;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              stmt = _ref[_i];
              _results.push(algebra(stmt, vars));
            }
            return _results;
          })()
        };
      },
      'data': function(data, vars) {
        return data;
      },
      'statement': match('statementType', 'algebra', {
        ELEMENT: function(stmt, vars) {
          return {
            type: 'statement',
            statementType: 'ELEMENT',
            expr: algebra(stmt.expr, vars)
          };
        },
        TRANS: function(stmt, vars) {
          return stmt;
        },
        SCALE: function(stmt, vars) {
          return stmt;
        },
        COORD: function(stmt, vars) {
          return stmt;
        },
        GUIDE: function(stmt, vars) {
          return stmt;
        }
      }),
      'function': function(fn, vars) {
        var arg;
        return {
          type: 'function',
          name: fn.name,
          args: (function() {
            var _i, _len, _ref, _results;
            _ref = fn.args;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              arg = _ref[_i];
              _results.push(algebra(arg, vars));
            }
            return _results;
          })()
        };
      },
      'cross': function(cross, vars) {
        var left, right;
        left = algebra(cross.left, vars);
        right = algebra(cross.right, vars);
        return Varset.cross(left, right);
      },
      'name': function(name, vars) {
        return Varset.fromVariable(vars[name.name]);
      }
    });
    step3 = match('type', 'step3', {
      'statements': function(stmts) {
        var scales, stmt;
        scales = (function() {
          var _i, _len, _ref, _results;
          _ref = stmts.statements;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            stmt = _ref[_i];
            _results.push(step3(stmt));
          }
          return _results;
        })();
        return _.extend.apply(null, scales);
      },
      'data': function(data) {
        return {};
      },
      'statement': match('statementType', 'step3.statement', {
        ELEMENT: function(stmt) {
          return {};
        },
        TRANS: function(stmt) {
          return {};
        },
        SCALE: function(stmt) {
          return step3(stmt.expr);
        },
        COORD: function(stmt) {
          return {};
        },
        GUIDE: function(stmt) {
          return {};
        }
      }),
      'function': match('name', 'step3.function', {
        'linear': function(fn) {
          var dim, result;
          if (fn.args.length !== 1) {
            throw Error('linear() expects one argument');
          }
          dim = step3(fn.args[0]);
          result = {};
          result[dim] = {
            type: 'linear'
          };
          return result;
        },
        'dim': function(fn) {
          if (fn.args.length !== 1) {
            throw Error('dim() expects one argument');
          }
          if (fn.args[0].type !== 'number') {
            throw Error('dim() expects a numeric argument');
          }
          return fn.args[0].value;
        }
      })
    });
    show = match('type', 'show', {
      statements: function(t) {
        var s;
        return ((function() {
          var _i, _len, _ref, _results;
          _ref = t.statements;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            s = _ref[_i];
            _results.push(show(s));
          }
          return _results;
        })()).join('\n');
      },
      statement: function(t) {
        return "" + t.statementType + ": " + (show(t.expr));
      },
      data: function(t) {
        return "DATA: " + t.newName + "=\"" + t.oldName + "\"";
      },
      name: function(t) {
        return t.name;
      },
      number: function(t) {
        return t.value;
      },
      string: function(t) {
        return t.value;
      },
      cross: function(t) {
        return "" + (show(t.left)) + "*" + (show(t.right));
      },
      assignment: function(t) {
        return "" + (show(t.left)) + "=" + (show(t.right));
      },
      "function": function(t) {
        var a;
        return "" + t.name + "(" + (((function() {
          var _i, _len, _ref, _results;
          _ref = t.args;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            a = _ref[_i];
            _results.push(show(a));
          }
          return _results;
        })()).join(',')) + ")";
      },
      varset: function(t) {
        return '<varset>';
      }
    });
    return {
      execute: execute,
      variables: variables,
      algebra: algebra,
      show: show
    };
  });

}).call(this);
