//@ sourceMappingURL=grammarOfGraphics.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/grammarOfGraphics/parser', 'cv/grammarOfGraphics/printTree', 'cv/grammarOfGraphics/step1_variables', 'cv/grammarOfGraphics/step2_algebra', 'cv/grammarOfGraphics/step3_scales'], function(parser, printTree, step1, step2, step3) {
    return function(variables, expression) {
      var tree;
      tree = parser.parse(expression);
      variables = step1(tree, variables);
      tree = step2(tree, variables);
      console.dir(step3(tree, variables));
      return tree;
    };
  });

}).call(this);
