//@ sourceMappingURL=match.map
// Generated by CoffeeScript 1.6.1
(function() {

  define([], function() {
    var match;
    return match = function(property, fnName, fns) {
      return function(obj) {
        var fn, key;
        key = obj[property];
        fn = fns[key];
        if (fn) {
          return fn.apply(null, arguments);
        } else {
          throw Error("no match for " + fnName + "." + property + " = " + key + ".\nObject = " + obj);
        }
      };
    };
  });

}).call(this);
