// Generated by CoffeeScript 1.6.1
(function() {

  define(['underscore'], function(_) {
    var methods;
    methods = {
      set: function(x, y) {
        this.x = x;
        this.y = y;
      }
    };
    return {
      create: function(x, y) {
        return _.extend({
          x: x,
          y: y
        }, methods);
      }
    };
  });

}).call(this);
