//@ sourceMappingURL=readCSV.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['jquery.csv', 'cv/Variable'], function(csv, Variable) {
    return function(fileName, callback) {
      return $.get(fileName, function(data) {
        var columnNames, i, key, m, name, table, tuple, tuples, variable, variables, variablesArr, _i, _j, _k, _len, _len1;
        table = $.csv.toArrays(data);
        columnNames = _.first(table);
        m = columnNames.length;
        tuples = _.rest(table);
        key = 0;
        variables = {};
        variablesArr = [];
        key = 0;
        for (_i = 0, _len = columnNames.length; _i < _len; _i++) {
          name = columnNames[_i];
          variablesArr.push(variables[name] = new Variable);
        }
        for (_j = 0, _len1 = tuples.length; _j < _len1; _j++) {
          tuple = tuples[_j];
          for (i = _k = 0; 0 <= m ? _k < m : _k > m; i = 0 <= m ? ++_k : --_k) {
            variable = variablesArr[i];
            variable.addEntry(key, tuple[i]);
          }
          key++;
        }
        return callback(null, variables);
      });
    };
  });

}).call(this);
