//@ sourceMappingURL=readCSV.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['jquery.csv', 'cv/Relation'], function(csv, Relation) {
    return function(fileName) {
      console.log('loading file ' + fileName);
      return $.get(fileName, function(data) {
        var attrNames, n, name, relation, table, tupleArrays, _i, _len;
        table = $.csv.toArrays(data);
        attrNames = _.first(table);
        console.log(attrNames);
        tupleArrays = _.rest(table);
        relation = new Relation;
        for (_i = 0, _len = attrNames.length; _i < _len; _i++) {
          name = attrNames[_i];
          relation.addAttribute(name);
        }
        n = attrNames.length;
        _.each(tupleArrays, function(tupleArr) {
          var i, tuple, _j;
          tuple = {};
          for (i = _j = 0; 0 <= n ? _j < n : _j > n; i = 0 <= n ? ++_j : --_j) {
            tuple[attrNames[i]] = tupleArr[i];
          }
          return relation.addTuple(tuple);
        });
        return relation.tuples.each(function(tuple) {
          return console.log(tuple.values);
        });
      });
    };
  });

}).call(this);
