//@ sourceMappingURL=Rectangle.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/expose'], function(expose) {
    return Backbone.Model.extend({
      initialize: function() {
        expose(this, 'x', 'y', 'w', 'h');
        if (!this.x) {
          this.x = 0;
        }
        if (!this.y) {
          this.y = 0;
        }
        if (!this.w) {
          this.w = 1;
        }
        if (!this.h) {
          return this.h = 1;
        }
      },
      copy: function(rectangle) {
        this.x = rectangle.x;
        this.y = rectangle.y;
        this.w = rectangle.w;
        return this.h = rectangle.h;
      }
    });
  });

}).call(this);
