// Generated by CoffeeScript 1.6.1
(function() {

  define(['backbone', 'cv/expose'], function(Backbone, expose) {
    return Backbone.Model.extend({
      initialize: function() {
        return expose(this, 'x', 'y', 'w', 'h');
      }
    });
  });

}).call(this);
