//@ sourceMappingURL=Relation.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/expose'], function(expose) {
    var Attribute, Relation, Tuple;
    Relation = Backbone.Model.extend({
      initialize: function() {
        this.attributes = new Backbone.Collection;
        this.tuples = new Backbone.Collection;
        return this.attrCounter = 0;
      },
      addAttribute: function(name) {
        var attribute;
        attribute = new Attribute({
          name: name,
          index: this.attrCounter++
        });
        this.attributes.add(attribute);
        return attribute;
      },
      addTuple: function(values) {
        return this.tuples.add(new Tuple({
          values: values
        }));
      },
      computeMinMax: function() {
        var _this = this;
        return this.attributes.each(function(attr) {
          var maxTuple, minTuple;
          minTuple = _this.tuples.min(function(tuple) {
            return tuple.value(attr);
          });
          maxTuple = _this.tuples.max(function(tuple) {
            return tuple.value(attr);
          });
          if (minTuple !== Infinity) {
            attr.min = minTuple.value(attr);
            return attr.max = maxTuple.value(attr);
          }
        });
      },
      select: function(test) {
        var result;
        result = new Relation;
        this.attributes.each(function(attr) {
          return result.addAttribute(attr.name);
        });
        result.tuples.add(this.tuples.filter(function(tuple) {
          return test(tuple.values);
        }));
        return result;
      },
      project: function(attrNames) {
        var name, result, _i, _len;
        result = new Relation;
        for (_i = 0, _len = attrNames.length; _i < _len; _i++) {
          name = attrNames[_i];
          result.addAttribute(name);
        }
        this.tuples.each(function(tuple) {
          return result.addTuple(_.pick(tuple.values, attrNames));
        });
        return result;
      }
    });
    Tuple = Backbone.Model.extend({
      initialize: function() {
        return expose(this, 'values');
      },
      value: function(attr) {
        return this.values[attr.index];
      }
    });
    Attribute = Backbone.Model.extend({
      initialize: function() {
        return expose(this, 'name', 'min', 'max', 'index');
      }
    });
    Relation.Attribute = Attribute;
    Relation.Tuple = Tuple;
    return Relation;
  });

}).call(this);
