//@ sourceMappingURL=Scale.map
// Generated by CoffeeScript 1.6.1
(function() {

  define([], function() {
    var Scale;
    return Scale = (function() {

      function Scale(dim, min, max) {
        this.dim = dim;
        this.min = min != null ? min : void 0;
        this.max = max != null ? max : void 0;
      }

      Scale.prototype.init = function(varset) {
        var i;
        i = this.dim - 1;
        if (this.min === void 0) {
          this.min = _.min(_.map(varset.tuples(), function(tuple) {
            return tuple[i];
          }));
        }
        if (this.max === void 0) {
          return this.max = _.max(_.map(varset.tuples(), function(tuple) {
            return tuple[i];
          }));
        }
      };

      Scale.prototype.value = function(tuple) {
        return (tuple[this.dim - 1] - this.min) / (this.max - this.min);
      };

      return Scale;

    })();
  });

}).call(this);
