//@ sourceMappingURL=Variable.map
// Generated by CoffeeScript 1.6.1
(function() {

  define([], function() {
    var Variable;
    return Variable = (function() {

      function Variable() {
        this._keysToValues = {};
      }

      Variable.prototype.addEntry = function(key, value) {
        return this._keysToValues[key] = value;
      };

      Variable.prototype.keys = function() {
        return _.keys(this._keysToValues);
      };

      Variable.prototype.values = function() {
        return _.values(this._keysToValues);
      };

      Variable.prototype.value = function(key) {
        return this._keysToValues[key];
      };

      return Variable;

    })();
  });

}).call(this);
