// Generated by CoffeeScript 1.6.1
(function() {

  define(['backbone'], function(Backbone) {
    var Viewport;
    Viewport = Backbone.Model.extend({
      srcToDest: function(inPt, outPt) {
        outPt.x = (inPt.x - (this.get('src')).x) / (this.get('src')).w * (this.get('dest')).w + (this.get('dest')).x;
        return outPt.y = (inPt.y - (this.get('src')).y) / (this.get('src')).h * (this.get('dest')).h + (this.get('dest')).y;
      },
      destToSrc: function(inPt, outPt) {
        outPt.x = (inPt.x - (this.get('dest')).x) / (this.get('dest')).w * (this.get('src')).w + (this.get('src')).x;
        return outPt.y = (inPt.y - (this.get('dest')).y) / (this.get('dest')).h * (this.get('src')).h + (this.get('src')).y;
      }
    });
    return {
      create: function(src, dest) {
        return new Viewport({
          src: src,
          dest: dest
        });
      }
    };
  });

}).call(this);
