// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/Container', 'cv/Viewport', 'cv/Rectangle', 'underscore'], function(Container, Viewport, Rectangle, _) {
    var add;
    add = function(superAdd, child) {
      if (!child.getBoundingBox) {
        throw Error("ViewportContainer.add(child) expects \nchild.getBoundingBox, a Rectangle to be projected \nfrom the viewport source bounds to the display \nbounds before calling child.paint().");
      }
      return superAdd(child);
    };
    return {
      create: function() {
        var container;
        container = {
          viewport: Viewport.create()
        };
        _.extend(container, Container.create({
          paint: function(ctx, bounds) {
            var _this = this;
            this.viewport.dest = bounds;
            return this.each(function(child) {
              return child.paint(ctx, _this.viewport.srcToDestRect(child.bounds));
            });
          }
        }));
        container.add = _.wrap(container.add, add);
        return container;
      }
    };
  });

}).call(this);
