// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/Container', 'cv/Viewport', 'underscore'], function(Container, Viewport, _) {
    return {
      create: function() {
        var container;
        return container = Container.create({
          paint: function(ctx, bounds) {
            return this.each(function(child) {
              return child.paint(ctx, bounds);
            });
          }
        });
      }
    };
  });

}).call(this);
