//@ sourceMappingURL=Viewport.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/expose'], function(expose) {
    var Viewport;
    return Viewport = Backbone.Model.extend({
      initialize: function() {
        return expose(this, 'src', 'dest');
      },
      srcToDest: function(inPt, outPt) {
        var d, s;
        s = this.src;
        d = this.dest;
        outPt.x = (inPt.x - s.x) / s.w * d.w + d.x;
        return outPt.y = (inPt.y - s.y) / s.h * d.h + d.y;
      },
      destToSrc: function(inPt, outPt) {
        var d, s;
        s = this.src;
        d = this.dest;
        outPt.x = (inPt.x - d.x) / d.w * s.w + s.x;
        return outPt.y = (inPt.y - d.y) / d.h * s.h + s.y;
      }
    });
  });

}).call(this);
