// Generated by CoffeeScript 1.6.1
(function() {

  define([], function() {
    var proto;
    proto = {
      srcToDest: function(inPt, outPt) {
        outPt.x = (inPt.x - this.src.x) / this.src.w * this.dest.w + this.dest.x;
        return outPt.y = (inPt.y - this.src.y) / this.src.h * this.dest.h + this.dest.y;
      },
      destToSrc: function(inPt, outPt) {
        outPt.x = (inPt.x - this.dest.x) / this.dest.w * this.src.w + this.src.x;
        return outPt.y = (inPt.y - this.dest.y) / this.dest.h * this.src.h + this.src.y;
      }
    };
    return {
      create: function(src, dest) {
        return Object.create(proto, {
          src: {
            value: src
          },
          dest: {
            value: dest
          }
        });
      }
    };
  });

}).call(this);
