//@ sourceMappingURL=step1_variables.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/match', 'cv/grammarOfGraphics/printTree'], function(match, printTree) {
    var dataStmts, variables;
    dataStmts = [];
    return variables = match('type', 'variables', {
      'statements': function(stmts, relation) {
        var a, attr, attrsToProject, b, d, dataStmt, stmt, _i, _j, _k, _len, _len1, _len2, _ref;
        dataStmts = [];
        _ref = stmts.statements;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          stmt = _ref[_i];
          variables(stmt);
        }
        for (_j = 0, _len1 = dataStmts.length; _j < _len1; _j++) {
          dataStmt = dataStmts[_j];
          a = dataStmt.oldName;
          b = dataStmt.newName;
          relation = relation.renameAttribute(a, b);
        }
        attrsToProject = [];
        for (_k = 0, _len2 = dataStmts.length; _k < _len2; _k++) {
          d = dataStmts[_k];
          attr = relation.attrByName(d.newName);
          attrsToProject.push(attr);
        }
        return relation.project(attrsToProject);
      },
      'data': function(data) {
        return dataStmts.push(data);
      },
      'statement': function() {}
    });
  });

}).call(this);
