//@ sourceMappingURL=step1_variables.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/match', 'cv/grammarOfGraphics/printTree'], function(match, printTree) {
    var dataStmts, variables;
    dataStmts = [];
    variables = match('type', 'variables', {
      'statements': function(stmts, relation) {
        var attr, attrsToProject, d, stmt, _i, _j, _len, _len1, _ref, _ref1;
        dataStmts = [];
        _ref = stmts.statements;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          stmt = _ref[_i];
          variables(stmt);
        }
        attrsToProject = [];
        for (_j = 0, _len1 = dataStmts.length; _j < _len1; _j++) {
          d = dataStmts[_j];
          _ref1 = relation.renameAttribute(d.oldName, d.newName), relation = _ref1[0], attr = _ref1[1];
          attrsToProject.push(attr);
        }
        return relation.project(attrsToProject);
      },
      'data': function(data) {
        return dataStmts.push(data);
      },
      'statement': function() {}
    });
    return variables;
  });

}).call(this);
