//@ sourceMappingURL=step2_algebra.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/match', 'cv/grammarOfGraphics/printTree'], function(match, printTree) {
    var step2;
    return step2 = match('type', 'step2', {
      'statements': function(stmts, variables) {
        var stmt, _i, _len, _ref, _results;
        _ref = stmts.statements;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          stmt = _ref[_i];
          _results.push(step2(stmt, variables));
        }
        return _results;
      },
      'data': function(data) {
        return data;
      },
      'statement': function(stmt) {
        return stmt;
      }
    });
  });

}).call(this);
