//@ sourceMappingURL=step1_variables.map
// Generated by CoffeeScript 1.6.1
(function() {

  define(['cv/match', 'cv/grammarOfGraphics/printTree'], function(match, printTree) {
    var dataStmts, step1;
    dataStmts = [];
    return step1 = match('type', 'step1', {
      'statements': function(stmts, variables) {
        var dataStmt, newName, oldName, stmt, _i, _j, _len, _len1, _ref;
        dataStmts = [];
        _ref = stmts.statements;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          stmt = _ref[_i];
          step1(stmt);
        }
        for (_j = 0, _len1 = dataStmts.length; _j < _len1; _j++) {
          dataStmt = dataStmts[_j];
          oldName = dataStmt.oldName;
          newName = dataStmt.newName;
          variables[newName] = variables[oldName];
        }
        return variables;
      },
      'data': function(data) {
        return dataStmts.push(data);
      },
      'statement': function() {}
    });
  });

}).call(this);
